# Generated by Django 3.0.7 on 2020-06-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0002_remove_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden'), ('moderated', 'moderated')], default='visible', max_length=20),
        ),
    ]
